name:  Bug Report
description: Reporta un error para ayudarnos a mejorarlo
title: "[BUG] "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Gracias por reportar este bug   
        Por favor completa la siguiente informaci贸n.

  - type: input
    id: summary
    attributes:
      label: Descripci贸n breve del error
      placeholder: Ej. El bot贸n de login no responde
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Pasos para reproducirlo
      description: Explica paso a paso c贸mo ocurre el error
      placeholder: |
        1. Ir a...
        2. Hacer clic en...
        3. Ocurre el error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamiento esperado
      placeholder: Deber铆a redirigir al dashboard
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Capturas de pantalla (opcional)
      description: Si aplica, adjunta im谩genes

  - type: input
    id: environment
    attributes:
      label: Entorno
      placeholder: Windows 11, Chrome 120, Node 20
